### PR TITLE
FileSystem UI Adjustments and Textures.

### PR DESCRIPTION
**Pull request by DI3HARD139**
Adjust and add textures for minimize and maximize buttons. Adjust Maximize button.

Notes: Ignore the disabled dofiles in the init.lua. That was so I could load the mod. See [Issue](https://github.com/Tmanyo/mineos/issues/1) for traceback.

### CODE REVIEW

**Comment by Tmanyo** [comment]
The dofile with webspider was a WIP.  I forgot to remove that dofile when I updated the files on GitHub.  I am going to review this and if everything works I will make a decision.

**Comment by Tmanyo** [comment]
I like the textures for Minimize, Maximize, and Close.  I think if they were sized down just a bit it would look a little better.  For the labels on the desktop icons, I thought about implementing something similar but forgot.  Instead of putting a label there, try using a tooltip.

`"tooltip[<gui_element_name>;<tooltip_text>]"`

That way, when you hover over it with a mouse it shows the name of the application.  I have tested this and it works.

[https://plus.google.com/photos/photo/108651544879565444112/6511030546310323826?authkey=CP-8l5zSt7iFAg&sqid=103288670101232495388&ssid=b66aa3c3-581e-4733-b4ed-cff3633b5822](url)

In-game screenshot does not show cursor, but it is over the NotePad element.

I added this to the formspec:
`"tooltip[notepad;Notepad]" ..`

I also appreciate the fork you made.  It made it super easy to test your changes!

**Comment by DI3HARD139** [comment]
I love that idea! Would save screen space for low res and mobile device users. (There will always be that one user). I agree with the resize of the Min, Max, Close buttons. Thought it might be a little too big but wanted input on em first.

**Comment by Tmanyo** [comment]
I have reviewed your latest commits.  I would suggest making the minimize button less wide.  I changed it from .35 to .32 and I thought it looked more proportional.  I also tried sizing down the X button just a tad, but the lines get thin and hard to see.  So I guess the X is fine.  The maximize button is perfect size in my opinion.  If you want to add the tooltips and change the size of the minimize buttons and apply it to all the applications, I will merge that all at once!

**Pull request merged**
